site_name: My Static Website
site_description: MkDocs / Material for MkDocs Example
site_url: https://example.com
repo_url: ""
repo_name: ""

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections

nav:
  - Home: pages/index.md
  - Content & Markdown: pages/content.md
  - Jupyter Notebook: pages/notebook.ipynb

plugins:
  # - search
  # - mermaid2
- mkdocs-jupyter:
    execute: false
    include_source: True
    custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js